spring:
  neo4j:
    uri: 
    authentication:
      username: 
      password: 
  datasource:
    username: 
    password: 
    url: 
server:
  port: 
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mybatis/*.xml
redis:
  port: 
  host: 
  password: 
  dbs: 